# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
theme: jekyll-theme-hacker
name: Game
title: WaveDash
email: wavedash2017@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  You must destroy the oncoming waves, but the only way is to cancel them out with another wave.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  wavedash-game

# github: "https://github.com/wavedash-game/wavedash" # Change from site repo to game repo
show_downloads: true

excerpt_separator: <!--sep-->

# Build settings
markdown: kramdown

# Gems
gems:
 - jemoji
 - jekyll-mentions
 - jekyll-seo-tag
